Josh Hoge

jsh10043@nyu.edu

NYU Tandon Data Science Bootcamp Week 2 Exercises


##Practice Questions for numpy

In [14]:
# Exercise 1
# Define two custom numpy arrays, say A and B.
# Generate two new numpy arrays by stacking A and B vertically and horizontally.

import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

C = np.vstack((A, B))
D = np.hstack((A, B))

print("Array C:\n",C,"\n")
print("Array D:\n",D)

Array C:
 [[1 2 3]
 [4 5 6]] 

Array D:
 [1 2 3 4 5 6]


In [15]:
# Exercise 2
# Find common elements between A and B. [Hint : Intersection of two sets]

import numpy as np

A = np.array([1, 2, 5])
B = np.array([4, 5, 6])

C = np.intersect1d(A, B)

print("Array A:\n",A,"\n")
print("Array B:\n",B,"\n")
print("Intersection of A and B:\n",C)

Array A:
 [1 2 5] 

Array B:
 [4 5 6] 

Intersection of A and B:
 [5]


In [21]:
# Exercise 3
# Extract all numbers from A which are within a specific range. eg between 5 and 10.
# [Hint: np.where() might be useful or boolean masks]

import numpy as np

A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])
low = 5
high = 10

print("Array A:\n",A,"\n")
print("Range:\n",low,"-",high,"\n")
print("Array elements in range:\n",A[(A > low) & (A < high)])


Array A:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13] 

Range:
 5 - 10 

Array elements in range:
 [6 7 8 9]


In [25]:
# Exercise 4
# Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# print ".0" after whole numbers for consistency
np.set_printoptions(formatter={'float_kind':lambda x: f'{x:.1f}'})

print("Rows with petallength > 1.5 and sepallength < 5.0:\n")
print(iris_2d[(iris_2d[:,2] > 1.5) & (iris_2d[:,0] < 5.0)])

Rows with petallength > 1.5 and sepallength < 5.0:

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1.0]
 [4.9 2.5 4.5 1.7]]


In [28]:
## Optional Practice Question
#Find the mean of a numeric column grouped by a categorical column in a 2D numpy array

import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4] # species

output = []
for group in np.unique(grouping_column):
    output.append([group, numeric_column[grouping_column==group].mean()])

print(output)


[[b'Iris-setosa', np.float64(3.418)], [b'Iris-versicolor', np.float64(2.7700000000000005)], [b'Iris-virginica', np.float64(2.974)]]


##Practice Questions for Pandas

In [29]:
# Exercise 1
# From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

import pandas as pd
import numpy as np

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

print(df[::20][['Manufacturer', 'Model', 'Type']])



   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [30]:
# Exercise 2
# Replace missing values in Min.Price and Max.Price columns with their respective mean.

import pandas as pd
import numpy as np

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')


df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())

print(df)

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31

In [33]:
# Exercise 3
# How to get the rows of a dataframe with row sum > 100?

import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

print("Original dataframe:\n")
print(df)
print("\nDataframe rows with sum > 100:\n")
print(df[df.sum(axis=1) > 100])

Original dataframe:

     0   1   2   3
0   28  21  20  18
1   20  31  37  36
2   36  17  34  10
3   19  36  32  32
4   37  13  32  22
5   30  15  30  39
6   32  19  36  29
7   13  39  38  17
8   15  30  26  25
9   38  18  35  23
10  12  28  10  35
11  13  16  21  13
12  14  13  37  30
13  25  17  34  21
14  32  18  21  37

Dataframe rows with sum > 100:

     0   1   2   3
1   20  31  37  36
3   19  36  32  32
4   37  13  32  22
5   30  15  30  39
6   32  19  36  29
7   13  39  38  17
9   38  18  35  23
14  32  18  21  37
